version: '3.8'

services:
  auth-postgres:
    image: postgres:15
    container_name: bm_auth_postgres
    restart: always
    environment:
      POSTGRES_USER: "${AUTH_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${AUTH_POSTGRES_PASSWORD}"
      POSTGRES_DB: "${AUTH_POSTGRES_DB}"
    ports:
      - "${AUTH_POSTGRES_PORT}"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  payment-postgres:
    image: postgres:15
    container_name: bm_payment_postgres
    restart: always
    environment:
      POSTGRES_USER: "${PAYMENT_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${PAYMENT_POSTGRES_PASSWORD}"
      POSTGRES_DB: "${PAYMENT_POSTGRES_DB}"
    ports:
      - "${PAYMENT_POSTGRES_PORT}"
    volumes:
      - payment_postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "${PGADMIN_PORT}"
    depends_on:
      - auth-postgres
      - payment-postgres

  # auth-service:
  #   build: .
  #   container_name: bm_auth_service
  #   restart: always
  #   ports:
  #     - "${AUTH_APP_PORT}"
  #   environment:
  #     AUTH_DATABASE_URL: "${AUTH_DATABASE_URL}"
  #     JWT_SECRET: "${JWT_SECRET}"
  #   depends_on:
  #     - auth-postgres

  # payment-service:
  #   build: .
  #   container_name: bm_payment_service
  #   restart: always
  #   environment:
  #     PAYMENT_DATABASE_URL: "${PAYMENT_DATABASE_URL}"
  #   depends_on:
  #     - payment-postgres

volumes:
  auth_postgres_data:
  payment_postgres_data:
